name: multipart_request
description: A flutter plugin to send a multipart request and get stream of progress.
version: 0.3.0
homepage: https://github.com/awazgyawali/multipart_request

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.brainants.multipartrequest
        pluginClass: MultipartRequestPlugin
      ios:
        pluginClass: MultipartRequestPlugin
